### ISSUE TITLE
How to wait for connection to complete before calling localstorage functions in client?

### ISSUE THREAD

**Issue by CaitlinWeb** [unadlib/origin-storage#24]
Thanks again for merging my PR! I'm still stuck on the `onConnect`/connection part so I have a few questions if you don't mind. I thought of a couple ways but they seem hacky to me, so wanted to get your input.

What's the purpose behind the required `onConnect` if `_isConnected` is `false` when it's called? 

How can I wait for the connection to be complete (ie `_isConnected = true`) before calling localforage functions? Do you have a working example you could share?

**Comment by unadlib** [comment]
In origin-storage v2.1.6, all async storage operations had to be ensured by using the `onConnect()` method.

I added the relevant logic. https://github.com/unadlib/origin-storage/commit/53c7a466ac28b55c6aeb00527f177d44da8fa8fd

In v2.1.7, if it's not yet connected, any async storage operations need to wait for a connection.

You can upgrade origin-storage to v2.1.7

**Comment by CaitlinWeb** [comment]
This is excellent, it's now working for me. Thank you so much for the quick turnaround! In v2.1.7 `onConnect` can be used as I expected to initialize.

For my use case I'm using the Adapter pattern to re-use the same code on my main site as the cross-domain sites. So can't really share my example. For anyone coming across this later you can do something like this.

client on `https://subdomain.example.com`:
```js
const client = new OriginStorageClient({
  uri: 'https://www.example.com/iframe.html',
  storageOptions: storeConfig,
  targetOrigin: 'https://www.example.com'
})
client.onConnect(function setup () {
  client.getItem('user').then(({ firstName, lastName }) => {
    console.log(firstName, lastName, this === client);
    // ...
  })
})
```

**Comment by CaitlinWeb** [comment]
Darn it was working but now I'm getting an error - probably didn't catch this sooner because of HMR or race condition. When the [connect promise is resolved](https://github.com/unadlib/origin-storage/blob/master/src/originStorageClient.ts#L78) in `OriginStorageClient`, `OriginStorage` may not have initialized localForage yet (`_localforage === undefined`).

```
index.cjs.development.js:3269 Uncaught (in promise) Error: 'getItem' error: TypeError: Cannot read properties of undefined (reading 'getItem')
    at OriginStorageClient.eval (index.cjs.development.js:3269:1)
    at Generator.next (<anonymous>)
    at fulfilled (index.cjs.development.js:155:1)
```

Maybe to complete the "handshake" OriginStorage should emit a `connected` event or something like that, which `OriginStorageClient` would listen for to set `_isConnect = true` and call `_connectResolve()`?

**Comment by unadlib** [comment]
I think there is something wrong here. 

```ts
  async connect() {
    if (!this._read && !this._write) {
      throw new Error(NoAccessError);
    }
    const config = await this.emit('connect');
    this._localforage = localforage.createInstance(config);
  }
```

That's what's right. 

```ts
  async connect() {
    if (!this._read && !this._write) {
      throw new Error(NoAccessError);
    }
    this._localforage = localforage.createInstance(config);
    const config = await this.emit('connect');
  }
```

It should make sure that localforage creates  the instance before responding to the connection.

**Comment by unadlib** [comment]
hi @CaitlinWeb , I reproduced this issue in the example and I have fixed the issue. You can update the version to 2.2.0.

**Comment by CaitlinWeb** [comment]
Thank you for the fix! It's working as expected now and I'll be using this for my project. Appreciate your work on this and for responding quickly 😄
